#!/bin/sh
#
# Copyright (c) 2012 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

iface="$2"
action="$1"

case "$action" in
    add)
        logger -s "network-slave udev $action $iface notify" 
        dbus-send --system --dest='com.citrix.xenclient.networkslave' --print-reply \
        / com.citrix.xenclient.networkslave.network_iface_notify string:"${action}" string:"${iface}" 
        ;;
    remove)
        dbus-send --system --dest='com.citrix.xenclient.networkslave' --print-reply \
        / com.citrix.xenclient.networkslave.network_iface_notify string:"${action}" string:"${iface}" 
        ;;
esac

